version: '3'

services:
  nodejs:
    image: node:12-alpine
    container_name: ohmycookie
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - VIRTUAL_HOST=ohmycookie.test,ohmycookie.glhf.lol
      - VIRTUAL_PORT=13337
    expose:
      - "13337"
    volumes:
      - .:/home/node/app
    command: npm run docker
    network_mode: bridge
